---
title: "Data1"
author: "Grace Rade"
date: "2023-03-24"
output: html_document
---
```{r}
library(tidyverse)
library(rio)
library(statnet)
```

```{r}
sandy_relief <- import("sandy2014.csv") ## source: https://www.govtrack.us/congress/votes/113-2013/s4 
highway_funds <- import("highway2014.csv") ## source: https://www.govtrack.us/congress/votes/113-2014/s248
harvey_relief <- import("harvey2018.csv") %>% 
  rename(person = "V1", state = "V2", district = "V3", vote = "V4", name = "V5", party = "V6") %>% 
  filter(!row_number() %in% c(1,2)) ## source: https://www.govtrack.us/congress/votes/115-2017/s192

water_infrastructure <- import("water2018.csv") ## source: https://www.govtrack.us/congress/votes/115-2018/s225

FEMA <- import("FEMA.csv") %>% 
  filter(disasterName == "HURRICANE SANDY" | disasterName == "HURRICANE HARVEY") %>% 
  distinct(stateCode, .keep_all = TRUE)
```

```{r}
## fix the senator names so its just first last
sandy_relief <- sandy_relief %>% 
  mutate(name = substr(name, 5,nchar(sandy_relief$name)-15)) %>% 
  select(-c(district, person))

highway_funds <- highway_funds %>% 
  mutate(name = substr(name, 5,nchar(highway_funds$name)-15)) %>% 
  select(-c(district, person))
  
harvey_relief <- harvey_relief  %>% 
  mutate(name = substr(name, 5,nchar(harvey_relief$name)-15)) %>% 
  select(-c(district, person))

water_infrastructure <- water_infrastructure %>% 
  mutate(name = substr(name, 5,nchar(water_infrastructure$name)-15)) %>% 
  select(-c(district, person))


## change the vote values from Yea/Nay/Not Voting to 0/1/NA
sandy_relief$vote[sandy_relief$vote == "Yea"] <- 1
sandy_relief$vote[sandy_relief$vote == "Nay"] <- 0
sandy_relief$vote[sandy_relief$vote == "Not Voting"] <- NA

highway_funds$vote[highway_funds$vote == "Yea"] <- 1
highway_funds$vote[highway_funds$vote == "Nay"] <- 0
highway_funds$vote[highway_funds$vote == "Not Voting"] <- NA

harvey_relief$vote[harvey_relief$vote == "Yea"] <- 1
harvey_relief$vote[harvey_relief$vote == "Nay"] <- 0
harvey_relief$vote[harvey_relief$vote == "Not Voting"] <-  NA

water_infrastructure$vote[water_infrastructure$vote == "Yea"] <- 1
water_infrastructure$vote[water_infrastructure$vote == "Nay"] <- 0
water_infrastructure$vote[water_infrastructure$vote == "Not Voting"] <- NA

```


```{r}
## making Sandy into dyadic data

sandy_relief <- sandy_relief %>% 
  mutate(name2 = name, state2 = state, party2 = party, vote2 = vote) ## make a copy of all the variables

sandy_combos <- sandy_relief %>% 
  expand(name, name2) %>% 
  filter(name != name2) ## expand the df to make all the possible pairs of senators

sandy1 <- sandy_relief %>% 
  select(state, name, vote, party) ## first senator

sandy2 <- sandy_relief %>% 
  select(state2, name2, vote2, party2) ## second senator

sandy_joined <- sandy_combos %>% 
  left_join(sandy1, by = "name") %>% 
  left_join(sandy2, by = "name2") %>% 
  mutate(cross_party = ifelse(party == party2, 1, 0), storm1 = ifelse(state %in% c("PA", "MA", "NH", "WV", "WA", "MD", "DE", "RI", "CT", "NJ", "NY"), 1, 0), storm2 = ifelse(state2 %in% c("PA", "MA", "NH", "WV", "WA", "MD", "DE", "RI", "CT", "NJ", "NY"), 1, 0), storm = ifelse(storm1 == 1 & storm2 == 1, 1, 0)) %>% 
  select(-c(storm1, storm2)) %>% 
  filter(vote == vote2) ## join the datasets together, create a cross party and shared storm variable, then only filter where the votes are the same

export(sandy_joined, "sandy_dyads.csv")

```

```{r}
## making sandy edge list into a network
library(network) ## load netowrk

sandy_sens <- nrow(sandy_relief)
net_sandy <-network.initialize(sandy_sens) ## initialize an empty network

network.vertex.names(x=net_sandy) <- sandy_relief$name ## name the vertices
```

