---
title: "harvey_net"
author: "Grace Rade"
date: "2023-04-23"
output: html_document
---
```{r}
library(tidyverse)
library(rio)
library(igraph)

harvey_relief <- import("harvey2018.csv")
harvey_relief <- harvey_relief %>% 
  rename(person = "V1", state = "V2", district = "V3", vote = "V4", name = "V5", party = "V6") %>% 
  filter(!row_number() %in% c(1,2)) %>% 
  mutate(name = substr(name, 6,nchar(sandy_relief$name)-15)) %>%
  mutate(storm = ifelse(state %in% c("TX", "LA"), 1, 0))

harvey_dyads <- import("harvey_dyads.csv")

harvey_net <- graph_from_data_frame(harvey_dyads, directed = F)
plot(harvey_net)
```

```{r}
#library(rio)
#library(tidyverse)
library(linkcomm)
library(concoR)
library(network)
library(statnet)
library(igraph)
library(intergraph)

harvey_dyads <- import("harvey_dyads.csv")
harvey_dyads2 <- import("harvey_dyads2.csv")
harvey_relief <- import("harvey2018.csv")

harvey_relief <-harvey_relief %>% 
  rename(person = "V1", state = "V2", district = "V3", vote = "V4", name = "V5", party = "V6") %>% 
  filter(!row_number() %in% c(1,2))

harvey_relief <- harvey_relief %>% 
  mutate(name = substr(name, 6,nchar(harvey_relief$name)-15)) %>% 
  mutate(storm = ifelse(state %in% c("TX", "LA"), 1, 0)) ## harvey relief just in case

harvey_el <- harvey_dyads %>% 
 select(name, name2) ## edge list

harvey_dyads2 <- harvey_dyads2 %>% 
  anti_join(harvey_dyads)
harvey_el2 <- harvey_dyads2 %>% 
  select(name, name2) ## edge list 2 of all the nodes not in the edge list (idk just spitballing)

## intiialize network and add names

net_harvey <- network.initialize(100) ## empty netowrk of 100 people
network.vertex.names(net_harvey) <- harvey_relief$name ## add in senator names

## add in edges
net_harvey[as.matrix(harvey_el)] <- 1 


set.vertex.attribute(net_harvey, "Storm State", harvey_relief$storm) ## set storm as a vertex attribute

set.edge.attribute(net_harvey, "Cross Party", harvey_dyads$cross_party) ## set edge attribute to cross party vote

## idk if messing with the edge lists will work, trying to get all the senators to be in the edge list
harvey_el <- harvey_el %>% 
  mutate(sharevote = 1)

harvey_el2 <- harvey_el2 %>% 
  mutate(sharevote = 0)

harvey_el3 <- harvey_el %>% 
  full_join(harvey_el2)

## start structural equivalence (get the blocks)
mat <- as.matrix.network.adjacency(net_harvey)
blocks <- equiv.clust(mat, method="euclidean") ## use equivalent clusters because they work on network objects

bm<-blockmodel(mat,blocks, k=2) ## blockmodel for the groups  (there are two blocks)

block2 <- as.data.frame(bm$block.membership)
block2$block <- block2$`bm$block.membership`
block2$name <-bm$plabels
block2$`bm$block.membership` <- NULL ## i have made a df of the blockmodel, sorting the whole senate into groups 

export(block2, "harvey_blocks.csv")
net_harvey2 <- asIgraph(net_harvey) ## convert this object to an igraph object 

modularity(net_harvey2, block2$block) ## calculate modularity, how to add the storm attribute though and cross party, not sure what to do next
## membership variable are the blocks

## my trying to at least make some progress in using our grouping variables

first_block <- harvey_relief %>% 
  full_join(block2) %>% 
  filter(block == 1) %>% 
  group_by(party, storm) %>% 
  summarize(number = n()) ## looking at the storm membership by party for block 1

second_block <- harvey_relief %>% 
  full_join(block2) %>% 
  filter(block == 2) %>% 
  group_by(party, storm) %>% 
  summarize(number = n()) ## looking at the storm membership by party for block 2

storm <- harvey_relief %>% 
  full_join(block2) %>% 
  group_by(storm, block) %>% 
  summarize(number = n()) ## looking at the storm membership by block

## not quite sure how to go about doing cross party variable, need to add it to the dyads but then i can't look at the blocks

cross_party1 <- harvey_dyads %>% 
  filter(cross_party == 1) %>% 
  group_by(storm) %>% 
  summarize(number = n()) ## look at number of shared storm in cross party ties

cross_party2 <- harvey_dyads %>% 
  group_by(cross_party, storm) %>% 
  summarize(number = n()) ## number of ties by cross party and storm
```
