---
title: "highway_net"
author: "Grace Rade"
date: "2023-04-23"
output: html_document
---
```{r}
library(tidyverse)
library(rio)
library(igraph)

highway_funds <- import("highway2014.csv")
highway_funds <- highway_funds %>% 
  mutate(name = substr(name, 6,nchar(highway_funds$name)-15)) %>% 
  mutate(storm = ifelse(state %in% c("PA", "MA", "NH", "WV", "WA", "MD", "DE", "RI", "CT", "NJ", "NY"), 1, 0))

highway_dyads <- import("highway_dyads.csv")

highway_net <- graph_from_data_frame(highway_dyads, directed = F)
plot(highway_net) ## also pretty modular
```

```{r}
library(rio)
library(tidyverse)
library(linkcomm)
library(concoR)
library(network)
library(statnet)
library(igraph)
library(intergraph)

highway_dyads <- import("highway_dyads.csv")
highway_dyads2 <- import("highway_dyads2.csv")
highway_funds <- import("highway2014.csv")

highway_funds <- highway_funds %>% 
  mutate(name = substr(name, 6,nchar(highway_funds$name)-15)) %>% 
  mutate(storm = ifelse(state %in% c("PA", "MA", "NH", "WV", "WA", "MD", "DE", "RI", "CT", "NJ", "NY"), 1, 0))

highway_el <- highway_dyads %>% 
 select(name, name2) ## edge list

highway_dyads2 <- highway_dyads2 %>% 
  anti_join(highway_dyads)
highway_el2 <- highway_dyads2 %>% 
  select(name, name2) ## edge list 2 of all the nodes not in the edge list (idk just spitballing)

## intiialize network and add names

net_highway <- network.initialize(100) ## empty netowrk of 100 people
network.vertex.names(net_highway) <- highway_funds$name ## add in senator names

## add in edges
net_highway[as.matrix(highway_el)] <- 1 

set.vertex.attribute(net_highway, "Storm State", highway_funds$storm) ## set storm as a vertex attribute

set.edge.attribute(net_highway, "Cross Party", highway_dyads$cross_party) ## set edge attribute to cross party vote

## idk if messing with the edge lists will work, trying to get all the senators to be in the edge list
highway_el <- highway_el %>% 
  mutate(sharevote = 1)

highway_el2 <- highway_el2 %>% 
  mutate(sharevote = 0)

highway_el3 <- highway_el %>% 
  full_join(highway_el2)

## start structural equivalence (get the blocks)
mat <- as.matrix.network.adjacency(net_highway)
blocks <- equiv.clust(mat, method="euclidean") ## use equivalent clusters because they work on network objects

bm<-blockmodel(mat,blocks, k=2) ## blockmodel for the groups  (there are two blocks)

block2 <- as.data.frame(bm$block.membership)
block2$block <- block2$`bm$block.membership`
block2$name <-bm$plabels
block2$`bm$block.membership` <- NULL ## i have made a df of the blockmodel, sorting the whole senate into groups 

net_highway2 <- asIgraph(net_highway) ## convert this object to an igraph object 

modularity(net_highway2, block2$block) ## calculate modularity, how to add the storm attribute though and cross party, not sure what to do next
## membership variable are the blocks

## my trying to at least make some progress in using our grouping variables

first_block <- highway_funds %>% 
  full_join(block2) %>% 
  filter(block == 1) %>% 
  group_by(party, storm) %>% 
  summarize(number = n()) ## looking at the storm membership by party for block 1

second_block <- highway_funds %>% 
  full_join(block2) %>% 
  filter(block == 2) %>% 
  group_by(party, storm) %>% 
  summarize(number = n()) ## looking at the storm membership by party for block 2

storm <- highway_funds %>% 
  full_join(block2) %>% 
  group_by(storm, block) %>% 
  summarize(number = n()) ## looking at the storm membership by block

## not quite sure how to go about doing cross party variable, need to add it to the dyads but then i can't look at the blocks

cross_party1 <- highway_dyads %>% 
  filter(cross_party == 1) %>% 
  group_by(storm) %>% 
  summarize(number = n()) ## look at number of shared storm in cross party ties

cross_party2 <- highway_dyads %>% 
  group_by(cross_party, storm) %>% 
  summarize(number = n()) ## number of ties by cross party and storm
```

