---
title: "sandy_net.Rmd"
author: "Grace Rade"
date: "2023-04-18"
output: 
  html_document:
    df_print: kable
---
```{r, warning = F, message = F}
library(rio)
library(tidyverse)
library(linkcomm)
library(concoR)
library(network)
library(statnet)
library(igraph)
library(intergraph)
library(knitr)

sandy_dyads <- import("sandy_dyads.csv")
sandy_dyads2 <- import("sandy_dyads2.csv")
sandy_relief <- import("sandy2014.csv")

sandy_relief <- sandy_relief %>% 
  mutate(name = substr(name, 6,nchar(sandy_relief$name)-15)) %>% 
  select(-c(district, person)) %>% 
  mutate(storm = ifelse(state %in% c("PA", "MA", "NH", "WV", "WA", "MD", "DE", "RI", "CT", "NJ", "NY"), 1, 0)) ## sandy relief just in case

sandy_el <- sandy_dyads %>% 
 select(name, name2) ## edge list

sandy_el_sings <- sandy_dyads %>% 
  edge.duplicates()

sandy_el_sings <- sandy_el_sings[2] %>% 
  as.data.frame(name = sandy_el_sings[1], name2 = sandy_el_sings[2]) %>% 
  rename(name = "edges.1", name2 = "edges.2") %>% 
  left_join(sandy_dyads)

sandy_dyads2 <- sandy_dyads2 %>% 
  anti_join(sandy_dyads)
sandy_el2 <- sandy_dyads2 %>% 
  select(name, name2) ## edge list 2 of all the nodes not in the edge list (idk just spitballing)

## intiialize network and add names

net_sandy <- network.initialize(100) ## empty netowrk of 100 people
network.vertex.names(net_sandy) <- sandy_relief$name ## add in senator names

## add in edges
net_sandy[as.matrix(sandy_el)] <- 1 
#net_sandy[as.matrix(sandy_el2)] <- 0 ## commented this out becuase it does not affect the modularity scores

set.vertex.attribute(net_sandy, "Storm State", sandy_relief$storm) ## set storm as a vertex attribute

set.edge.attribute(net_sandy, "Cross Party", sandy_dyads$cross_party) ## set edge attribute to cross party vote

## idk if messing with the edge lists will work, trying to get all the senators to be in the edge list
sandy_el <- sandy_el %>% 
  mutate(sharevote = 1)

sandy_el2 <- sandy_el2 %>% 
  mutate(sharevote = 0)

sandy_el3 <- sandy_el %>% 
  full_join(sandy_el2)

## start structural equivalence (get the blocks)
mat <- as.matrix.network.adjacency(net_sandy)
blocks <- equiv.clust(mat, method="euclidean") ## use equivalent clusters because they work on network objects

bm<-blockmodel(mat,blocks, k=2) ## blockmodel for the groups  (there are two blocks)

block2 <- as.data.frame(bm$block.membership)
block2$block <- block2$`bm$block.membership`
block2$name <-bm$plabels
block2$`bm$block.membership` <- NULL ## i have made a df of the blockmodel, sorting the whole senate into groups 

export(block2, "sandy_blocks.csv")
net_sandy2 <- asIgraph(net_sandy) ## convert this object to an igraph object 

modularity(net_sandy2, block2$block) ## calculate modularity, how to add the storm attribute though and cross party, not sure what to do next
## membership variable are the blocks

## my trying to at least make some progress in using our grouping variables

first_block <- sandy_relief %>% 
  full_join(block2) %>% 
  filter(block == 1) %>% 
  group_by(party, storm) %>% 
  summarize(number = n()) ## looking at the storm membership by party for block 1

first_block

second_block <- sandy_relief %>% 
  full_join(block2) %>% 
  filter(block == 2) %>% 
  group_by(party, storm) %>% 
  summarize(number = n()) ## looking at the storm membership by party for block 2

second_block

storm <- sandy_relief %>% 
  full_join(block2) %>% 
  group_by(storm, block) %>% 
  summarize(number = n()) ## looking at the storm membership by block

## not quite sure how to go about doing cross party variable, need to add it to the dyads but then i can't look at the blocks

cross_party1 <- sandy_el_sings %>% 
  filter(cross_party == 0) %>% 
  group_by(storm) %>% 
  summarize(number = n()) ## look at number of shared storm in cross party ties

cross_party2 <- sandy_dyads %>% 
  group_by(cross_party, storm) %>% 
  summarize(number = n()) ## number of ties by cross party and storm
```

```{r, fig.caption = "Hurricane Sandy and Highway Funding Block 1 Membership by Party and Storm Status"}
first_block
```

